#input values
first_name = input('First name:  ')
last_name = input('Last name:  ')
email = input('Email address:  ')
phone = input('Phone number:  ')
job = input('Job title:  ')
id_number = input('ID number:  ')
hair = input('Hair color:  ')
eyes = input('Eye color:  ')
month = input('Month you started:  ')
training = input('Have you completed your training?  ')

#out values (id card)
print(f'-' * 40)
print(f'{last_name.upper()}, {first_name.title()}')
print(f'{job.title()}')
print(f'ID: {id_number}\n')
print(f'{email.lower()}')
print(f'{phone}\n')
print(f'Hair: {hair.title():14} Eyes: {eyes.title()}')
print(f'Month: {month.title():13} Training: {training.title()}')
print(f'-' * 40)